#!/usr/bin/env sh
branch="$(git rev-parse --abbrev-ref HEAD)"
. "$(dirname -- "$0")/_/husky.sh"

if [ "$branch" = "master" ]; then
  echo "You can't push directly to master branch."
  exit 1
fi

if [ "$branch" = "main" ]; then
  echo "You can't push directly to main branch."
  exit 1
fi

