name: Deploy app to github pages
on:
  push:
    branches: ["main", "develop"]
  workflow_dispatch:
# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write
# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true
jobs:
 test-code:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "17"
      - name: Install Dependencies
        run: npm install
      - name: Test Lint
        run: npm run lint
      - name: Test coverage
        run: npm run test
      - name: Create PR
        run: gh pr create --title "Synchronizing branches." --body "Synchronization" --base main --head develop/main-develop
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Approve PR
        run: gh pr merge -m
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  build:
    if: github.event.pull_request.merged == 'true'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "17"
      - name: Install Dependencies
        run: npm install
      - name: Build
        run: CI=false npm run build
      - name: Run test
        run: npm run test
      - name: Upload page artifact
        uses: actions/upload-pages-artifact@v1.0.4
        with:
          path: "./build"
  deploy:
    needs: build
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to gh-pages
        id: deployment
        uses: actions/deploy-pages@v1