name: Upload develop changes and pull request to main.
on:
  pull_request:
  push:
    branches:
      - develop/*
jobs:
  test-code:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "17"
      - name: Install Dependencies
        run: npm install
      - name: Test Lint
        run: npm run lint
      - name: Test coverage
        run: npm run test
      - name: Create PR
        uses: medlypharmacy/create-pr-action@main
        enviroment: github-pages
          GITHUB_TOKEN: ${{secrets.TOKEN}}
          HEAD_BRANCH: develop/main-develop
          BASE_BRANCH: main         
      - name: Curl request
        run: curl -X POST -d {} https://api.netlify.com/build_hooks/6365398559976d009f2aed7d