name: Upload develop changes and pull request to main.
on:
  pull_request:
  push:
    branches:
      - develop/*
jobs:
  test-code:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "17"
      - name: Install Dependencies
        run: npm install
      - name: Test Lint
        run: npm run lint
      - name: Test coverage
        run: npm run test
       - name: Create Pull Request to main
        uses: peter-evans/create-pull-request@v4
        with:
          branch: main
          assignees: IsmaelCamacho-Hexaware
          reviewers: IsmaelCamacho-Hexaware