name: Pull request to netlify
on:
  pull_request:
    branches:
      - main
      - master
      - develop/*
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Curl request
      run: curl -X POST -d {} https://merry-beijinho-b404c5.netlify.app/  